"""
Django settings for roll_check project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-4&o2i$3avzqw1m3ski&5ts5*zn!i+%(v_$#%y9)ad=$(oyfp5q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['10.1.21.13', 'localhost', 'g5s2jh39-7004.inc1.devtunnels.ms', 'api.herofashion.com']
ALLOWED_HOSTS = ['app.herofashion.com','127.0.0.1']


# CSRF_TRUSTED_ORIGINS = [

#     'https://g5s2jh39-7004.inc1.devtunnels.ms/',
#     'https://api.herofashion.com',
#     'http://10.1.21.13:7006/'
# ]

# CORS_ALLOWED_ORIGINS = [
#     "https://api.herofashion.com",
#     "http://localhost:3000",
   
    
# ]


# CORS_ALLOW_CREDENTIALS = True

# CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_SAMESITE = 'None'  # Required for cross-origin
# CSRF_COOKIE_HTTPONLY = False   # JS needs to read it

# SESSION_COOKIE_SECURE = True
# SESSION_COOKIE_SAMESITE = 'None'


# X_FRAME_OPTIONS = 'ALLOWALL'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'roll',
    'pwa',
    'corsheaders',
    'welcome',
    'attendance',
    'lay_spreading',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'roll_check.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                
                'django.template.context_processors.request',
                'welcome.context_processors.user_permissions',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'roll_check.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'demo': {
            'ENGINE': 'mssql',
            'NAME': 'Tally2sql',
            'USER': 'sa',
            'PASSWORD': 'Fashion@01',
            'HOST': '10.1.21.11',
            'PORT': '1433',
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'trusted_connection': "yes"
            }
    },
    'demo1': {
            'ENGINE': 'mssql',
            'NAME': 'NewPowerBi',
            'USER': 'sa',
            'PASSWORD': 'Fashion@01',
            'HOST': '10.1.21.11',
            'PORT': '1433',
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'trusted_connection': "yes"
            }
    },
    'main': {
            'ENGINE': 'mssql',
            'NAME': 'Garmentrk',
            'USER': 'sa',
            'PASSWORD': 'Fashion@01',
            'HOST': '10.1.21.11',
            'PORT': '1433',
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'trusted_connection': "yes"
            }
    },

    'test': {
            'ENGINE': 'mssql',
            'NAME': 'testerphero',
            'USER': 'sa',
            'PASSWORD': 'Fashion@01',
            'HOST': '10.1.21.11',
            'PORT': '1433',
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'trusted_connection': "yes"
            }
    },
}

LOGIN_URL = '/login/'
# LOGIN_REDIRECT_URL = 'group-login/'
# LOGOUT_REDIRECT_URL = '/login/'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# 👇 Required for `collectstatic` to work
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 👇 Tell Django where to find app-level static folders
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'roll/static'),
]

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# MEDIA_URL = '/staff_images/'
# MEDIA_ROOT = r'\\10.1.21.11\D\Staff_Employee_Images'  


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STAFF_IMAGES_URL = '/staff_images/'
STAFF_IMAGES_ROOT = r'\\10.1.21.11\D\Staff_Employee_Images'


ORDER_IMAGES_URL = '/order_image/'
ORDER_IMAGES_ROOT = r'\\10.1.21.11\d\Order_Images'


PRO_URL = '/pro_image/'
PRO_ROOT = r'\\10.1.21.11\d\Order_Images\export'


ALL_URL = '/all_image/'
ALL_ROOT = r'\\adminserver\H\All images\export'





DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



PWA_APP_NAME = 'HeroFashion'
PWA_APP_DESCRIPTION = "My Django PWA Application"
PWA_APP_THEME_COLOR = '#000000'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
# PWA_APP_ORIENTATION = 'portrait'
PWA_APP_ORIENTATION = 'landscape'  # ✅ orientation direction
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'

PWA_APP_ICONS = [
    {
        'src': '/static/images/image.png',
        'sizes': '192x192',
        'type': 'image/png',
    },
    {
        'src': '/static/images/image.png',
        'sizes': '512x512',
        'type': 'image/png',
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/images/image.png',
        'sizes': '192x192'
    },
    {
        'src': '/static/images/image.png',
        'sizes': '512x512'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        "src": "/static/images/splash-2048x2732.png",
        "media": "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)"
    },
    {
        "src": "/static/images/splash-1668x2388.png",
        "media": "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)"
    },
    {
        "src": "/static/images/splash-1668x2224.png",
        "media": "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)"
    },
    {
        "src": "/static/images/splash-1536x2048.png",
        "media": "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)"
    },
    # Add for iPhones too if needed
]
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'roll/static/js/serviceworker.js')
