# Generated by Django 5.2.5 on 2025-09-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lay_spreading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_lock',
            fields=[
                ('table_no_1', models.BooleanField()),
                ('table_no_2', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
