# Generated by Django 5.2.5 on 2025-09-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lay_spreading', '0002_table_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='lay_data_update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('timer', models.CharField(max_length=50)),
                ('brown_sheet_timer', models.CharField(max_length=50)),
                ('join_marker_timer', models.CharField(max_length=50)),
                ('plan_no', models.CharField(max_length=50)),
                ('job_no', models.CharField(max_length=50)),
                ('marker_no', models.CharField(max_length=50)),
            ],
        ),
    ]
