# Generated by Django 5.2.5 on 2025-09-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lay_spreading', '0003_lay_data_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lay_data_update',
            name='brown_sheet_timer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lay_data_update',
            name='job_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lay_data_update',
            name='join_marker_timer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lay_data_update',
            name='marker_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lay_data_update',
            name='plan_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
