# Generated by Django 5.2.5 on 2025-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lay_spreading', '0004_alter_lay_data_update_brown_sheet_timer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrsCplan4',
            fields=[
                ('planno', models.IntegerField(db_column='Planno')),
                ('markerno', models.IntegerField()),
                ('rlno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('planwgt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('ply', models.IntegerField(blank=True, null=True)),
                ('planmtr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estply', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('usdanthr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('rlwgt', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('fdia', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('rejwgt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sl', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Trs_cplan4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='roll_data_update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('timer', models.CharField(max_length=50)),
                ('plan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('job_no', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('f_dia', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_ply', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_obwgt', models.CharField(blank=True, max_length=50, null=True)),
                ('req_wgt', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_dia', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_ply', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_obwgt', models.CharField(blank=True, max_length=50, null=True)),
                ('end_bit', models.CharField(blank=True, max_length=50, null=True)),
                ('bal_wgt', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
