# Generated by Django 5.2.5 on 2025-09-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lay_spreading', '0005_trscplan4_roll_data_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_plans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('job_no', models.CharField(blank=True, max_length=50, null=True)),
                ('marker_no', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=50, null=True)),
                ('fabric_color', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('timer', models.CharField(max_length=50)),
            ],
        ),
    ]
