# Generated by Django 5.2.5 on 2025-09-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lay_spreading', '0006_final_plans'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='final_plans',
            table='final_plans',
        ),
    ]
