# Generated by Django 5.2.5 on 2025-09-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lay_spreading', '0007_alter_final_plans_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll_data_update',
            name='scl_wgt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
