# Generated by Django 5.2.5 on 2025-09-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='powerbi_data',
            field=models.BooleanField(default=False),
        ),
    ]
