# Generated by Django 5.2.5 on 2025-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_userpermission_powerbi_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='lay_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='lay_spreading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='production_data',
            field=models.BooleanField(default=False),
        ),
    ]
