# Generated by Django 5.2.5 on 2025-10-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_userpermission_lay_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueOverall1',
            fields=[
                ('o_ordqty', models.IntegerField(blank=True, null=True)),
                ('o_merch', models.CharField(blank=True, max_length=35, null=True)),
                ('Image', models.CharField(blank=True, db_column='filnam', max_length=82, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('jobno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('topbottom_des', models.CharField(blank=True, db_column='TopBottom_des', max_length=50, null=True)),
                ('clr', models.CharField(blank=True, max_length=50, null=True)),
                ('bc', models.IntegerField(blank=True, null=True)),
                ('sew', models.IntegerField(blank=True, null=True)),
                ('tc', models.IntegerField(blank=True, null=True)),
                ('fc', models.IntegerField(blank=True, null=True)),
                ('ir', models.IntegerField(blank=True, null=True)),
                ('pac', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vue_overall1',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='userpermission',
            name='unit1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='unit2',
            field=models.BooleanField(default=False),
        ),
    ]
