# Generated by Django 5.2.5 on 2025-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_vueoverall1_userpermission_unit1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='merch1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='merch2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='unit3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='unit4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='unit5',
            field=models.BooleanField(default=False),
        ),
    ]
