# Generated by Django 5.2.5 on 2025-10-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_allotpen_empattendancefact_fabfabricstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='server10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='server15',
            field=models.BooleanField(default=False),
        ),
    ]
