# Generated by Django 5.2.5 on 2025-10-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_userpermission_server10_userpermission_server15'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='bill',
            field=models.BooleanField(default=False),
        ),
    ]
