# Generated by Django 5.2.5 on 2025-10-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_allotpen1_ordsamplestatus_ordsamplestatus1_printnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBuyer',
            fields=[
                ('buyerid', models.IntegerField(db_column='BuyerID', primary_key=True, serialize=False)),
                ('buyername', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BuyerName', max_length=50, null=True)),
                ('orderno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='OrderNo', max_length=50, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('guid', models.CharField(blank=True, db_column='Guid', max_length=36, null=True)),
                ('refresh', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Refresh', max_length=50, null=True)),
            ],
            options={
                'db_table': 't_buyer',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='fabfabricstatus',
            table='Fab_Fabric_Status1',
        ),
    ]
