# Generated by Django 5.2.5 on 2025-10-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0010_tbuyer_alter_fabfabricstatus_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overall',
            fields=[
                ('o_ordqty', models.IntegerField(blank=True, null=True)),
                ('o_buyer', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='o_Buyer', max_length=40, null=True)),
                ('stylename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='StyleName', max_length=50)),
                ('o_merch', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=35, null=True)),
                ('filnam', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=82, null=True)),
                ('unit', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('jobno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, primary_key=True, serialize=False)),
                ('topbottom_des', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TopBottom_des', max_length=50, null=True)),
                ('clr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('bc', models.IntegerField(blank=True, null=True)),
                ('sew', models.IntegerField(blank=True, null=True)),
                ('tc', models.IntegerField(blank=True, null=True)),
                ('fc', models.IntegerField(blank=True, null=True)),
                ('ir', models.IntegerField(blank=True, null=True)),
                ('pac', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vue_overall1',
                'managed': False,
            },
        ),
    ]
