# Generated by Django 5.2.5 on 2025-09-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punchdtls1',
            fields=[
                ('unitname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Unitname', max_length=50, null=True)),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('shift', models.IntegerField(blank=True, null=True)),
                ('intime', models.DateTimeField(blank=True, null=True)),
                ('outtime', models.DateTimeField(blank=True, null=True)),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('latemin', models.IntegerField(blank=True, null=True)),
                ('wrk_cat', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25, null=True)),
                ('a_intime', models.DateTimeField(blank=True, null=True)),
                ('a_outtime', models.DateTimeField(blank=True, null=True)),
                ('o_intime', models.DateTimeField(blank=True, null=True)),
                ('o_outtime', models.DateTimeField(blank=True, null=True)),
                ('br_out', models.DateTimeField(blank=True, null=True)),
                ('br_in', models.DateTimeField(blank=True, null=True)),
                ('br_out1', models.DateTimeField(blank=True, null=True)),
                ('br_in1', models.DateTimeField(blank=True, null=True)),
                ('id1', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PunchDtls1',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Unitatt',
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
