# Generated by Django 5.2.5 on 2025-09-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0002_punchdtls1_delete_unitatt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_roll_update',
            name='m1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m12',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='master_roll_update',
            name='m9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
