# Generated by Django 5.2.5 on 2025-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0003_alter_master_roll_update_m1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueFindia',
            fields=[
                ('rownum', models.BigIntegerField(db_column='RowNum', primary_key=True, serialize=False)),
                ('orderno', models.CharField(db_column='OrderNo', max_length=50)),
                ('colour', models.CharField(blank=True, db_column='Colour', max_length=50, null=True)),
                ('fabric', models.CharField(db_column='Fabric', max_length=35)),
                ('dia', models.CharField(db_column='Dia', max_length=35)),
                ('finaldia', models.CharField(blank=True, db_column='FinalDia', max_length=20, null=True)),
            ],
            options={
                'db_table': 'vue_findia',
                'managed': False,
            },
        ),
    ]
