# Generated by Django 5.2.5 on 2025-10-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0004_vuefindia'),
    ]

    operations = [
        migrations.CreateModel(
            name='back_permissions',
            fields=[
                ('Emp_id', models.IntegerField()),
                ('Password', models.CharField(max_length=6)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
