# Generated by Django 5.2.5 on 2025-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0006_breaktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_final_mistake',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
