# Generated by Django 5.2.5 on 2025-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAge',
            fields=[
                ('no', models.IntegerField(db_column='No', primary_key=True, serialize=False)),
                ('edate', models.DateTimeField(db_column='EDate')),
                ('billdate', models.DateTimeField(db_column='BillDate')),
                ('billno', models.CharField(db_column='BillNo', max_length=50)),
                ('module', models.CharField(blank=True, db_column='Module', max_length=50, null=True)),
                ('suppliers', models.CharField(blank=True, db_column='Suppliers', max_length=35, null=True)),
                ('employees', models.CharField(blank=True, db_column='Employees', max_length=35, null=True)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=4, max_digits=19)),
                ('billpassed', models.SmallIntegerField(db_column='BillPassed')),
                ('br_ageing', models.IntegerField(blank=True, db_column='BR Ageing', null=True)),
                ('billdate_ageing', models.IntegerField(blank=True, db_column='BillDate Ageing', null=True)),
            ],
            options={
                'db_table': 'bill_age',
                'managed': False,
            },
        ),
    ]
