# Generated by Django 5.2.5 on 2025-10-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_billage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignDtls',
            fields=[
                ('slno', models.BigIntegerField(db_column='SlNo', primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('photo', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dept', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('joindt', models.DateTimeField(blank=True, db_column='JoinDt', null=True)),
                ('resigndt', models.DateTimeField(blank=True, db_column='resignDt', null=True)),
                ('days_worked', models.IntegerField(blank=True, db_column='Days_Worked', null=True)),
            ],
            options={
                'db_table': 'vue_resign_Dtls',
                'managed': False,
            },
        ),
    ]
